Audit v2 vault remediation
credbull/credbull-defi pull request #87
Opened 2024-07-30 09:59 UTC by Krishnakumarskr

2024-07-31 05:37 UTC, jplodge-pro requested changes

2024-07-31 05:37 UTC, jplodge-pro commented on packages/contracts/src/plugin/WhiteListPlugin.sol
> +    IWhiteListProvider public immutable WHITELIST_PROVIDER;
All uppercase is for [constants](https://docs.soliditylang.org/en/v0.8.26/style-guide.html#constants) not `immutable` state variables (which are just state variables).

2024-08-02 14:08 UTC, lucasia requested changes
Please kindly update as per suggestions.

2024-08-02 14:08 UTC, lucasia commented on packages/contracts/src/vault/MaturityVault.sol
> -        checkMaturity = status;
similar, let's keep the function taking a bool as an argument and rename it to be setMaturityCheck(bool _checkMaturity)

2024-08-06 09:45 UTC, Krishnakumarskr commented on packages/contracts/src/plugin/MaxCapPlugin.sol
>      error CredbullVault__MaxCapReached();
It's to set the maximum deposit amount that can be deposited by the users collectively to the vault.
ERC20Capped doesn't fit here as it is related to setting maxcap to mint ERC20 tokens.

2024-08-13 12:33 UTC, lucasia approved these changes

2024-08-13 12:33 UTC, lucasia commented on packages/contracts/src/vault/FixedYieldVault.sol
>      }
this should follow the same convention - take a bool status and be renamed from toggleWindowCheck to setWindowCheck

2024-08-13 13:44 UTC, merged